# Basic Settings
title: Priv360 • La confidentialité est notre affaire
description: Nous optimisons vos programmes de conformité en matière de protection des données personnelles et de vie privée, augmentant vos opportunités de croissances.
author: Priv360
# Language format language_TERRITORY. Default is en_US
lang: fr_CA
# website logos, images & icons
logo: img/chklst.png
image: img/header.jpg
# urls
url: https://priv360.com
english_url: ''
# french landing page
french_url: /fr
baseurl: ''
# french resources page
resources_url: 'resources'
# french services page
services_url: 'fr-services'

# copyright text in footer
copyright: Priv360

# email address
email: contact@dario.com
email_username: contact@dario.com
# email address in privacy policy
email_privacy: contact@dario.com

# contact telephone number
telephone_number: +1 514 558 4573

# search tracking id for Priv360.com
google_tracking_id: UA-98131817-5

webmaster_verifications:
  google: 
  bing: 
  alexa:
  yandex:
  baidu:

# Social/SEO
twitter_username:
facebook_username:

twitter:
  username:

facebook:
  app_id:
  publisher:
  admins:

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "NOTICE", "LICENSE", "README.md"]

# gems
gems:
  - jekyll-seo-tag
 
# Build settings
markdown: kramdown
